//! The wildcard-SAN vs. excluded-dNSName-nameConstraint scenario from
//! [draft-beck-lamps-leafy-greens-00](https://datatracker.ietf.org/doc/html/draft-beck-lamps-leafy-greens-00).
//!
//! The fixtures in `examples/leafy_greens` are an ECDSA (P-256) chain generated by
//! `~/devel/leafy-greens-test/certs/gen.sh`:
//!
//! ```text
//! Root CA (root.der)  ->  Intermediate CA (intermediate.der)  ->  end entity
//!                          nameConstraints = critical, excluded; DNS:foo.example.com
//! ```
//!
//! Under RFC 5280's lexical dNSName matching, `*` is just another label, so the wildcard leaf
//! `*.example.com` is not within the excluded subtree `foo.example.com` and the path validates;
//! a literal `foo.example.com` leaf is rejected. Either way certval records the excluded subtree it
//! processed in `PR_FINAL_EXCLUDED_SUBTREES` so a caller (e.g., a GUI) can display it — the point
//! the draft makes about surfacing the constraint that the wildcard bypasses.
#![cfg(feature = "std")]

use certval::environment::pki_environment::PkiEnvironment;
use certval::path_settings::*;
use certval::validator::path_validator::*;
use certval::*;

// 2027-01-01T00:00:00Z, within every fixture's validity window (EEs: 2026-07-06 .. 2027-08-07),
// pinned so the test does not become time-dependent as the fixtures approach expiry.
const TOI: u64 = 1_798_761_600;

const ROOT: &[u8] = include_bytes!("examples/leafy_greens/root.der");
// The plain intermediate asserts only excluded; DNS:foo.example.com.
const INTERMEDIATE: &[u8] = include_bytes!("examples/leafy_greens/intermediate.der");
// The permit intermediate asserts permitted; DNS:example.com alongside the same exclusion.
const INTERMEDIATE_PERMIT: &[u8] = include_bytes!("examples/leafy_greens/intermediate-permit.der");

/// Builds the Root -> Intermediate -> EE path and runs RFC 5280 validation at the pinned time of
/// interest, returning the result and the results object so callers can inspect recorded state.
fn validate(der_ca: &[u8], der_ee: &[u8]) -> (certval::Result<()>, CertificationPathResults) {
    let mut ta = PDVTrustAnchorChoice::try_from(ROOT).unwrap();
    ta.parse_extensions(EXTS_OF_INTEREST);

    let mut ta_source = TaSource::new();
    ta_source.push(CertFile {
        filename: "root.der".to_string(),
        bytes: ROOT.to_vec(),
    });
    ta_source.initialize().unwrap();

    let mut ca = PDVCertificate::try_from(der_ca).unwrap();
    ca.parse_extensions(EXTS_OF_INTEREST);
    let mut ee = PDVCertificate::try_from(der_ee).unwrap();
    ee.parse_extensions(EXTS_OF_INTEREST);

    let mut pe = PkiEnvironment::new();
    pe.populate_5280_pki_environment();
    pe.add_trust_anchor_source(Box::new(ta_source));

    let mut cert_path = CertificationPath::new(ta, vec![ca], ee);
    let mut cps = CertificationPathSettings::new();
    cps.set_time_of_interest(TimeOfInterest::from_unix_secs(TOI).unwrap());
    let mut cpr = CertificationPathResults::new();
    let r = pe.validate_path(&pe, &cps, &mut cert_path, &mut cpr);
    (r, cpr)
}

/// Asserts that the recorded terminal name-constraints state reflects the intermediate: the excluded
/// set carries `DNS:foo.example.com` and the permitted set is unconstrained (no dNSName subtree).
fn assert_records_excluded_foo(cpr: &CertificationPathResults) {
    let excluded = cpr
        .get_final_excluded_subtrees()
        .expect("excluded subtrees recorded on success");
    let excluded = name_constraints_set_to_name_constraints_settings(&excluded).unwrap();
    assert_eq!(
        excluded.dns_name,
        Some(vec!["foo.example.com".to_string()]),
        "terminal excluded set should carry the intermediate's excluded dNSName"
    );

    let permitted = cpr
        .get_final_permitted_subtrees()
        .expect("permitted subtrees recorded on success");
    assert!(
        permitted.dns_name.is_empty(),
        "the intermediate asserts no permitted subtree, so dNSName stays unconstrained"
    );
}

#[test]
fn good_leaf_validates_and_records_excluded_subtree() {
    // good.example.com is lexically outside the excluded subtree foo.example.com: the path validates
    // and the excluded subtree it was validated against is recorded for display.
    let ee = include_bytes!("examples/leafy_greens/ee-good.der");
    let (r, cpr) = validate(INTERMEDIATE, ee);
    assert!(
        r.is_ok(),
        "good.example.com is not within excluded foo.example.com"
    );
    assert_records_excluded_foo(&cpr);
}

#[test]
fn wildcard_leaf_bypasses_exclusion_and_records_subtree() {
    // The draft's bite: *.example.com is not lexically within foo.example.com, so RFC 5280
    // name-constraint validation passes even though RFC 9525 lets *.example.com match the reference
    // identity foo.example.com in TLS. certval still records the excluded subtree it processed, which
    // is what lets a frontend surface the constraint the wildcard slips past.
    let ee = include_bytes!("examples/leafy_greens/ee-wildcard.der");
    let (r, cpr) = validate(INTERMEDIATE, ee);
    assert!(
        r.is_ok(),
        "*.example.com is lexically outside excluded foo.example.com"
    );
    assert_records_excluded_foo(&cpr);
}

#[test]
fn literal_leaf_rejected_by_exclusion() {
    // The negative control: a literal foo.example.com leaf is within the excluded subtree and is
    // rejected, proving the constraint works for literal names (so the wildcard is the real bypass).
    // A name-constraints failure returns early before the terminal state is recorded.
    let ee = include_bytes!("examples/leafy_greens/ee-literal.der");
    let (r, cpr) = validate(INTERMEDIATE, ee);
    assert_eq!(
        r.err(),
        Some(Error::PathValidation(
            PathValidationStatus::NameConstraintsViolation
        )),
        "literal foo.example.com is within the excluded subtree"
    );
    assert!(cpr.get_final_permitted_subtrees().is_none());
    assert!(cpr.get_final_excluded_subtrees().is_none());
}

#[test]
fn wildcard_leaf_records_both_permitted_and_excluded_under_permit_intermediate() {
    // The permit intermediate asserts permitted; DNS:example.com in addition to the exclusion. The
    // wildcard *.example.com falls within the permitted subtree and (lexically) outside the excluded
    // one, so the path validates and both operative subtrees are recorded — the case a caller needs
    // to weigh the wildcard against, and the only leaf here exercising the permitted-side recording.
    let ee = include_bytes!("examples/leafy_greens/ee-permit.der");
    let (r, cpr) = validate(INTERMEDIATE_PERMIT, ee);
    assert!(
        r.is_ok(),
        "*.example.com is within permitted example.com and outside excluded foo.example.com"
    );

    let permitted = cpr
        .get_final_permitted_subtrees()
        .expect("permitted subtrees recorded on success");
    let permitted = name_constraints_set_to_name_constraints_settings(&permitted).unwrap();
    assert_eq!(permitted.dns_name, Some(vec!["example.com".to_string()]));

    let excluded = cpr
        .get_final_excluded_subtrees()
        .expect("excluded subtrees recorded on success");
    let excluded = name_constraints_set_to_name_constraints_settings(&excluded).unwrap();
    assert_eq!(excluded.dns_name, Some(vec!["foo.example.com".to_string()]));
}
