//! Trust stores the service holds, as the CBOR pairs every PITTv3 frontend already consumes.
//!
//! Two sources, and the difference between them is worth keeping in view. The **built-in** stores
//! are generated from the `certval_stores_*` providers when this crate is built (see `build.rs`),
//! so every certificate in one has a citable origin and the browser's copy of the same store is the
//! same material by construction. A **configured** store is whatever a deployment put in the
//! `--stores` directory, which may be an export from a desktop run, a store built for one
//! community, or a graph assembled by chasing — good reasons to serve it, and no way for this crate
//! to say where its certificates came from. [`StoreProvenance`] rides along in the catalog listing
//! so a client can say which it offered rather than presenting the two as peers.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use bytes::Bytes;
use log::{info, warn};
use serde::{Deserialize, Serialize};

/// Where a store's material came from, which is the whole of what this service can say about how
/// far it should be trusted.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum StoreProvenance {
    /// Generated from a certval trust store provider when the service was built. The provider
    /// carries checked-in DER or a published bundle and asserts a conformance check over it, so a
    /// certificate here is one the community published.
    Provider,
    /// Read from the directory the deployment configured. How its certificates were gathered is
    /// between the deployment and whoever built the store.
    Configured,
}

/// One trust store: the trust anchors and the CA certificates as separate CBOR artifacts, which is
/// the pair `pittv3 -g` writes and the desktop's Export PKI Environment button produces.
///
/// The halves are [`Bytes`] rather than `Vec<u8>` because serving one is then a reference count
/// instead of a copy — the Mozilla CA store alone is 6.6 MB — and because a built-in store's halves
/// are `'static`, so they are shared with the binary image rather than read onto the heap.
#[derive(Clone, Debug)]
pub struct StoreEntry {
    /// Identifier used in URIs and in a validation request's `store_id`.
    pub id: String,
    /// Name shown to a person choosing a store.
    pub label: String,
    /// Serialized trust anchor store.
    pub ta_cbor: Bytes,
    /// Serialized CA certificate store, including the partial paths discovered when it was built.
    /// Empty for an anchors-only store.
    pub ca_cbor: Bytes,
    /// Where the material came from.
    pub provenance: StoreProvenance,
}

/// How a store is described to a client.
///
/// The URIs rather than the bytes are returned so the browser fetches a store only when one is
/// selected, and so the shape matches the table the browser application already carries for the
/// stores it ships with. The same selector then renders both without knowing which is which.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct StoreDescriptor {
    /// Identifier to name in a validation request.
    pub id: String,
    /// Name to show.
    pub label: String,
    /// URI of the trust anchor CBOR.
    pub ta_url: String,
    /// URI of the CA certificate CBOR, absent for a store carrying trust anchors alone. Absent
    /// rather than a URI serving nothing, so a client asks for what exists instead of learning that
    /// a store has no intermediates by fetching an empty artifact.
    pub ca_url: Option<String>,
    /// Where the material came from.
    pub provenance: StoreProvenance,
}

/// Trust material generated by `build.rs` from a provider environment and linked in. Empty when the
/// `builtin-stores` feature is off, which is why the fields are read nowhere in that build.
#[cfg_attr(not(feature = "builtin-stores"), allow(dead_code))]
struct Builtin {
    /// Identifier, matching the artifact names `pittv3-wasm/build.rs` writes for the same
    /// environment so the browser recognizes a store it already ships.
    id: &'static str,
    /// Name shown to a person choosing a store.
    label: &'static str,
    /// Serialized trust anchor store.
    ta_cbor: &'static [u8],
    /// Serialized CA certificate store, absent for an anchors-only environment.
    ca_cbor: Option<&'static [u8]>,
}

include!(concat!(env!("OUT_DIR"), "/builtin_stores.rs"));

/// Stores read at startup and held in memory.
///
/// Reading them once rather than per request keeps a validation from touching the filesystem at
/// all, which matters because the same validation code runs in a browser where there is no
/// filesystem to touch.
#[derive(Debug, Default)]
pub struct StoreCatalog {
    entries: BTreeMap<String, StoreEntry>,
}

impl StoreCatalog {
    /// Returns a catalog holding nothing, for a deployment that offers only the relay or that
    /// expects every client to bring its own trust anchors.
    pub fn empty() -> Self {
        StoreCatalog::default()
    }

    /// Returns the stores generated from the trust store providers when the service was built, so a
    /// deployment that configures no store directory still has something to offer.
    ///
    /// Empty when the crate was built without `builtin-stores`.
    pub fn builtin() -> Self {
        let entries = BUILTIN
            .iter()
            .map(|b| {
                (
                    b.id.to_string(),
                    StoreEntry {
                        id: b.id.to_string(),
                        label: b.label.to_string(),
                        ta_cbor: Bytes::from_static(b.ta_cbor),
                        ca_cbor: b.ca_cbor.map_or_else(Bytes::new, Bytes::from_static),
                        provenance: StoreProvenance::Provider,
                    },
                )
            })
            .collect();
        StoreCatalog { entries }
    }

    /// Adds every store in `other`, which replaces one of the same identifier already held.
    ///
    /// Configuration wins over what was built in, and deliberately: a deployment naming a store is
    /// making a choice, and the likeliest reason to name one this service already carries is to
    /// serve material fresher than the build. The replacement is logged, since a store quietly
    /// standing in for a built-in of the same name is exactly the kind of thing to be able to find
    /// in a log afterwards.
    pub fn merge(&mut self, other: StoreCatalog) {
        for (id, entry) in other.entries {
            if let Some(replaced) = self.entries.insert(id, entry) {
                info!(
                    "Trust store {} from the store directory replaces the built-in of the same name",
                    replaced.id
                );
            }
        }
    }

    /// Reads every store in `dir`, in whichever of the three layouts the artifact already has --
    /// nothing here asks a deployment to rename what a PITTv3 tool produced:
    ///
    /// - **`<id>/ta.cbor` and `<id>/ca.cbor` in a subdirectory**, which is what the desktop's
    ///   Export PKI Environment writes; the directory name is the identifier.
    /// - **`<id>_ta.cbor` and `<id>_ca.cbor`**, which is how the trust store providers name their
    ///   generated artifacts.
    /// - **`<id>.ta.cbor` and `<id>.ca.cbor`**.
    ///
    /// A trust anchor artifact with no CA artifact beside it is loaded with an empty CA store,
    /// since trust anchors alone validate a directly-issued certificate; a CA artifact with no
    /// trust anchors is skipped, because a graph with nothing to anchor it validates nothing.
    ///
    /// Display names come from `stores.json` when it is present, as an object mapping identifier to
    /// name; anything not named there falls back to the identifier.
    pub fn load(dir: &Path) -> std::io::Result<Self> {
        let labels = read_labels(dir);
        let mut entries = BTreeMap::new();

        for entry in fs::read_dir(dir)? {
            let path = entry?.path();
            let name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };

            let (id, ta_path, ca_path) = if path.is_dir() {
                (name, path.join("ta.cbor"), path.join("ca.cbor"))
            } else {
                // The two-dot form is tried first: a file named `x.ta.cbor` also ends in `a.cbor`
                // for the underscore rule to misread if the order were reversed.
                let split = name
                    .strip_suffix(".ta.cbor")
                    .map(|id| (id, "."))
                    .or_else(|| name.strip_suffix("_ta.cbor").map(|id| (id, "_")));
                match split {
                    Some((id, sep)) => (
                        id.to_string(),
                        path.clone(),
                        path.with_file_name(format!("{id}{sep}ca.cbor")),
                    ),
                    None => continue,
                }
            };

            if !ta_path.is_file() {
                continue;
            }
            let ta_cbor = Bytes::from(fs::read(&ta_path)?);
            let ca_cbor = match ca_path.is_file() {
                true => Bytes::from(fs::read(&ca_path)?),
                false => Bytes::new(),
            };
            info!(
                "Loaded trust store {id} ({} bytes of trust anchors, {} bytes of CA certificates)",
                ta_cbor.len(),
                ca_cbor.len()
            );
            let label = labels.get(&id).cloned().unwrap_or_else(|| id.clone());
            entries.insert(
                id.clone(),
                StoreEntry {
                    id,
                    label,
                    ta_cbor,
                    ca_cbor,
                    provenance: StoreProvenance::Configured,
                },
            );
        }
        Ok(StoreCatalog { entries })
    }

    /// Returns the store with the given identifier.
    pub fn get(&self, id: &str) -> Option<&StoreEntry> {
        self.entries.get(id)
    }

    /// Describes every store for a client's selector, with URIs relative to the service root so the
    /// descriptors survive being served from behind a path prefix.
    pub fn listing(&self) -> Vec<StoreDescriptor> {
        self.entries
            .values()
            .map(|e| StoreDescriptor {
                id: e.id.clone(),
                label: e.label.clone(),
                ta_url: format!("stores/{}/ta.cbor", e.id),
                ca_url: match e.ca_cbor.is_empty() {
                    true => None,
                    false => Some(format!("stores/{}/ca.cbor", e.id)),
                },
                provenance: e.provenance,
            })
            .collect()
    }

    /// Returns how many stores were loaded.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Reports whether any store was loaded.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Reads the optional `stores.json` naming each store for display. Wording that reads well ("DoD
/// NIPR PROD") cannot be derived from a file name, and a CBOR store carries certificates rather
/// than a title for the collection, so it has to be stated somewhere; a deployment that does not
/// care omits the file and gets identifiers. A file that is present but unreadable is reported
/// rather than ignored, since silently falling back to identifiers looks like the file was
/// disregarded.
fn read_labels(dir: &Path) -> BTreeMap<String, String> {
    let path = dir.join("stores.json");
    if !path.is_file() {
        return BTreeMap::new();
    }
    match fs::read(&path).map(|b| serde_json::from_slice::<BTreeMap<String, String>>(&b)) {
        Ok(Ok(labels)) => labels,
        Ok(Err(e)) => {
            warn!("Ignoring {}: {e}", path.display());
            BTreeMap::new()
        }
        Err(e) => {
            warn!("Ignoring {}: {e}", path.display());
            BTreeMap::new()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_every_layout_a_pittv3_tool_produces() {
        let dir = tempfile::tempdir().unwrap();

        // What Export PKI Environment writes: a folder holding fixed names.
        let exported = dir.path().join("my_export");
        fs::create_dir(&exported).unwrap();
        fs::write(exported.join("ta.cbor"), b"ta").unwrap();
        fs::write(exported.join("ca.cbor"), b"ca").unwrap();

        // What the trust store providers generate.
        fs::write(dir.path().join("dod_nipr_prod_ta.cbor"), b"ta").unwrap();
        fs::write(dir.path().join("dod_nipr_prod_ca.cbor"), b"ca").unwrap();

        fs::write(dir.path().join("pkits_ml_dsa.ta.cbor"), b"ta").unwrap();
        fs::write(dir.path().join("pkits_ml_dsa.ca.cbor"), b"ca").unwrap();

        // Trust anchors with no CA store beside them are usable; a CA store with no trust anchors
        // is not, and a file that is part of no store at all is ignored.
        fs::write(dir.path().join("anchors_only.ta.cbor"), b"ta").unwrap();
        fs::write(dir.path().join("orphan.ca.cbor"), b"ca").unwrap();
        fs::write(dir.path().join("notes.txt"), b"x").unwrap();

        let catalog = StoreCatalog::load(dir.path()).unwrap();

        assert_eq!(catalog.len(), 4);
        assert_eq!(catalog.get("my_export").unwrap().ca_cbor.as_ref(), b"ca");
        assert_eq!(
            catalog.get("dod_nipr_prod").unwrap().ca_cbor.as_ref(),
            b"ca"
        );
        assert_eq!(catalog.get("pkits_ml_dsa").unwrap().ca_cbor.as_ref(), b"ca");
        assert!(catalog.get("anchors_only").unwrap().ca_cbor.is_empty());
        assert!(catalog.get("orphan").is_none());

        // Absent a stores.json, the identifier stands in for a name, and the URIs are the ones the
        // artifact layout never shows through. A store with no intermediates offers no URI for
        // them rather than one that would serve nothing.
        let listing = catalog.listing();
        assert_eq!(listing[0].id, "anchors_only");
        assert_eq!(listing[0].label, "anchors_only");
        assert_eq!(listing[0].ca_url, None);
        assert_eq!(listing[3].ta_url, "stores/pkits_ml_dsa/ta.cbor");
        assert_eq!(
            listing[3].ca_url.as_deref(),
            Some("stores/pkits_ml_dsa/ca.cbor")
        );

        // Everything read from a directory is configured material: the service can say where it
        // found it and nothing about where its certificates came from.
        assert!(listing
            .iter()
            .all(|d| d.provenance == StoreProvenance::Configured));
    }

    #[test]
    fn names_come_from_stores_json_when_it_is_there() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("dod_nipr_prod_ta.cbor"), b"ta").unwrap();
        fs::write(dir.path().join("unnamed.ta.cbor"), b"ta").unwrap();
        fs::write(
            dir.path().join("stores.json"),
            br#"{"dod_nipr_prod": "DoD NIPR PROD"}"#,
        )
        .unwrap();

        let catalog = StoreCatalog::load(dir.path()).unwrap();
        assert_eq!(catalog.get("dod_nipr_prod").unwrap().label, "DoD NIPR PROD");
        assert_eq!(catalog.get("unnamed").unwrap().label, "unnamed");

        // A manifest that cannot be read leaves the stores loaded rather than failing the startup
        // that would otherwise have served them.
        fs::write(dir.path().join("stores.json"), b"{not json").unwrap();
        let catalog = StoreCatalog::load(dir.path()).unwrap();
        assert_eq!(catalog.len(), 2);
        assert_eq!(catalog.get("dod_nipr_prod").unwrap().label, "dod_nipr_prod");
    }

    /// The built-in stores have to be the material a run can actually use, not merely bytes the
    /// build script wrote: a trust anchor store certval loads and finds anchors in, and a CA store
    /// wherever the catalog claims one. This is the only place the generated table is checked
    /// against what it claims to be.
    #[cfg(feature = "builtin-stores")]
    #[test]
    fn built_in_stores_are_loadable_material() {
        use certval::{CertSource, CertVector, TaSource};

        let catalog = StoreCatalog::builtin();
        assert!(!catalog.is_empty(), "the build script generated no stores");

        for descriptor in catalog.listing() {
            let entry = catalog.get(&descriptor.id).unwrap();
            assert_eq!(entry.provenance, StoreProvenance::Provider);

            let ta = TaSource::new_from_cbor(&entry.ta_cbor)
                .unwrap_or_else(|e| panic!("{} wrote an unloadable TA store: {e:?}", entry.id));
            assert!(!ta.is_empty(), "{} anchors nothing", entry.id);

            assert_eq!(
                descriptor.ca_url.is_some(),
                !entry.ca_cbor.is_empty(),
                "{} offers a CA store it does not carry, or carries one it does not offer",
                entry.id
            );
            if !entry.ca_cbor.is_empty() {
                CertSource::new_from_cbor(&entry.ca_cbor)
                    .unwrap_or_else(|e| panic!("{} wrote an unloadable CA store: {e:?}", entry.id));
            }
        }
    }

    /// The two sources compose the way the flag descriptions say: the directory augments the
    /// built-ins, and where both name a store the configured one is served. A deployment that
    /// points at a store directory is choosing, and the choice has to survive the built-ins being
    /// there.
    #[test]
    fn a_configured_store_augments_the_built_ins_and_wins_where_they_collide() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("local_pki_ta.cbor"), b"ta").unwrap();

        let mut catalog = StoreCatalog::builtin();
        let built_in = catalog.len();
        let overridden = catalog.listing().first().map(|d| d.id.clone());
        if let Some(id) = &overridden {
            fs::write(dir.path().join(format!("{id}_ta.cbor")), b"replacement").unwrap();
        }

        catalog.merge(StoreCatalog::load(dir.path()).unwrap());

        assert_eq!(catalog.len(), built_in + 1, "the new store was not added");
        assert_eq!(
            catalog.get("local_pki").unwrap().provenance,
            StoreProvenance::Configured
        );
        if let Some(id) = &overridden {
            let entry = catalog.get(id).unwrap();
            assert_eq!(entry.ta_cbor.as_ref(), b"replacement");
            assert_eq!(entry.provenance, StoreProvenance::Configured);
        }
    }
}
